[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "beans"
version = "0.9.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "platformdirs>=4.3.8",
    "pyqt6>=6.9.1",
    "usefullog>=0.8.4",
]
[project.scripts]
beans = "src.BEANS.run:main"